export default class Language{
    name = '';
    lang = {} as any;
    loaded = {langru: false, langen: false};
    langru = {        
        mainm_home: 'Главная',
        mainm_about: 'Компания',
        mainm_support: 'Поддержка',
        mainm_policy:  'Политика конфиденциальности и cookies',
        mainm_lowinfo:  'Юридическая информация',
        log_log: 'Вход',
        log_log_title: "Добро пожаловать",
        log_log_text: 'Пожалуйста, введите ваше имя пользователя и пароль для доступа к вашей учетной записи.',
        log_forgotuser: 'Забыли свое имя пользователя?',
        log_forgotpass: 'Забыли пароль?',
        log_email: 'Email',
        log_pass: 'Пароль',
        log_pass_er: 'Необходим пароль',
        log_saveses: 'Запомнить сессию',
        log_enter: 'Войти',
        log_er: 'Ваш Email и пароль введены неправильно.\nВводите Email и пароль без пробелов.\nИспользуйте английскую раскладку клавиатуры.Если Вам необходима помощь, Вы можете обратиться в нашу техническую поддержку через Email: ',
        log_worktime: 'Пн-Пт с 10 до 18 (мск)',
        reg_reg: 'Регистрация',
        reg_reg_text: 'Пожалуйста, заполните требуемые поля для создания учетной записи.',
        reg_email: 'Email',        
        reg_phone: 'Телефон (формат: код и номер)',        
        reg_postcode: 'Почтовый индекс',        
        reg_lname: 'Фамилия (только латинские буквы)',
        reg_fname: 'Имя (только латинские буквы)',
        reg_passcan: 'Скан паспорта с фотографией, персональными данными и местом регистрации в PDF формате',        
        reg_passcanchoose: 'Выберите файл',
        reg_passcanbig_er: 'Размер файла превышает 10 Мб',
        reg_passcanpdf_er: 'Выберите файл в формате PDF',
        reg_agree: "Соглашаюсь на сбор и обработку персональных данных",
        reg_cancel: "Отменить",
        reg_continue: "Продолжить",
        reg_back: "Назад",
        reg_ok: "Регистрация учетной записи прошла успешно. При входе в учетную запись введите свой Email и пароль, которые были отправлены на адрес электронной почты, указанный при регистрации.",
        code_btncancel: 'Отменить',
        code_btnconfirm: 'Отправить',
        code_btngetcode: 'Получить код',
        code_confirminfo: 'Введите код и подтвердите операцию',
        code_confirmremark: 'Сообщение с одноразовым паролем отправлено на вашу личную почту $1.\nЕсли вы не получили письмо в течении трех минут, система предложит повторить отправку кода.',
        http400_er: 'Некорректный запрос.\nЗа помощью обратитесь в нашу техническую поддержку через Email: ',
        http401_er: 'Доступ к ресурсу запрещен.\nПользователь не авторизован. Пройдите процедуру ввода Email и пароля',
        http403_er: 'Доступ к ресурсу запрещен.\nЗа помощью обратитесь в нашу техническую поддержку через Email: ',
        http404ref_er: 'Реферальная ссылка не соответствует ни одному партнеру. За уточнением обратитесь к владельцу реферальной ссылки',
        http404user_er: 'Пользователь не найден.\nВводите Email и пароль без пробелов.\nИспользуйте английскую раскладку клавиатуры.',
        http404receiver_er: 'Получатель не найден\nЗа уточнением обратитесь к владельцу счета.',
        http500_er: 'Сервис недоступен.\nИнтернет соединение прерывается.\nПопробуйте подключится к другой сети.',
        notfound_er: 'не найден',
        routenotfound_er: 'Путь не найден',
        policytext: "Политика конфиденциальности и использования файлов cookie",
        support_page:"Центр поддержки",
        support_title:"На этой странице вы найдёте необходимую информацию о каждой услуге. Остались вопросы? Свяжитесь с нами, используя контактные данные, представленные ниже.",
        support_legal:"Юридическая информация и документы",
        support_compinfo:"Центр обслуживания клиентов",        
        support_compinfo_email: "Корпоративная почта:",        
        support_compinfo_time_title: "Часы работы:",
        support_compinfo_time_text: "10:00 - 17:00 (по центральноевропейскому времени) с понедельника по пятницу",
        hungup_title: "Вы вышли из системы.",
        hungup_text: "Благодарим вас за использование наших сервисов.",
        hungup_text1: "Для обеспечения дополнительной безопасности мы рекомендуем вам регулярно очищать кэш браузера и избегать сохранения учётных данных.",
        hangup_again: "Войти снова",
        hangup_stepon: "Перейти на ",
        ipaddress: "IP-адрес",
        home_title: "Ваши преимущества с ",
        home_title1: "Надежность. Точность. Прогресс",
        home_title2: "Работаем на благо клиента",
        home_title3: " Наше кредо-надежность, стабильность, швейцарское качество",
        home_title4: "Перемены к лучшему начинаются с нас. Открой путь к своему успеху!",
        home_title5: "Сберечь. Сохранить. Приумножить",
        home_title6: "Мы работаем на ваше благо 24/7",
        home_title7: "Твоя финансовая свобода-здесь",
        home_title8: "Мы управляем финансами для твоего благополучия",
        home_title9: "Верное решение-залог успеха",
        about_title: "О Компании",       
        about_media: "Наши мероприятия"
    };
    langen = {
        mainm_home: 'Home',
        mainm_about: 'Company',
        mainm_support: 'Support',
        mainm_policy:  'Privacy & Cookies Policy',
        mainm_lowinfo:  'Legal Information',
        log_log: 'Log in',
        log_log_title: 'Welcome',
        log_log_text: 'Please enter your username and password to access your account.',
        log_forgotuser: 'Forgot your username?',
        log_forgotpass: 'Forgot your password?',
        log_email: 'Email',
        log_pass: 'Password',
        log_pass_er: 'Password is required',
        log_saveses: 'Keep me sign',
        log_enter: 'Log in',
        log_er: 'Your Email and Password were entered incorrectly.\nEnter your Email and Password without spaces. Use an English keyboard layout.\nIf you need help, you can contact our technical support via Email: ',
        log_worktime: 'Mo-Fr from 10 tо 18 (mos)',
        reg_reg: 'Register',
        reg_reg_text: 'Please fill in the required fields to create an account.',
        reg_email: 'Email',        
        reg_phone: 'Phone (format: code and number)',        
        reg_postcode: 'Postcode',  
        reg_lname: 'Last name (only latin letters)',
        reg_fname: 'First name (only latin letters)',      
        reg_passcan: 'Passport scan with photo, personal data and place of registration in PDF format',        
        reg_passcanchoose: 'Select file',
        reg_passcanbig_er: 'The file size exceeds 10 MB',
        reg_passcanfmt_er: 'Select PDF file',
        reg_agree: "I agree to the collection and processing of personal data",
        reg_cancel: "Cancel",
        reg_continue: "Continue",
        reg_back: "Back",
        reg_ok: "Account registration was successful. When entering your account, enter your Email and password that was sent to your email address specified during registration.",
        code_btncancel: 'Cancel',
        code_btnconfirm: 'Submit',
        code_btngetcode: 'Get code',
        code_confirminfo: 'Enter the code and confirm the operation',
        code_confirmremark: 'A message with a one-time password has been sent to your personal mail $1.\nIf you have not received the letter within three minutes, the system will offer to resend the code.',
        http400_er: 'Invalid request.\nFor help, contact our technical support via Email: ',
        http401_er: 'Access to the resource is denied.\nThe user is not authorized.\nGo through the procedure for entering your Email and Password.',
        http403_er: 'Access to the resource is denied.\nFor help, contact our technical support via Email: ',
        http404ref_er: 'The referral link does not match any partner.\nFor clarification, contact the owner of the referral link ',
        http404user_er: 'User not found.\nEnter your Email and password without spaces.\nPlease use the English keyboard layout.',
        http404receiver_er: 'The recipient was not found.\nPlease contact the account holder for clarification.',
        http500_er: 'Service unavailable.\nThe Internet connection is interrupted.\nTry connecting to a different network.',
        notfound_er: 'not found',
        routenotfound_er: 'Route not found',
        policytext: "Privacy and Cookies Policy",
        support_page:"Support Hub",
        support_title:"Find the essential information and resources for each service on this page. Still have questions? Get in touch using the contact details below.",
        support_legal:"Legal information & documents",
        support_compinfo:"Customer Care Center",
        support_compinfo_time_title: "Opening hours:",
        support_compinfo_time_text: "10:00 - 17:00 CET Monday to Friday",
        hungup_title: "You are now logged out.",
        hungup_text: "Thank you for using our services.",
        hungup_text1: "For extra security, we recommend that you regularly clear your browser's cache and avoid saving your credentials.",
        hangup_again: "Login again",
        hangup_stepon: "Go to ",
        ipaddress: "IP-address",
        home_title: "Your benefits with ",
        home_title1: "Reliability. Accuracy. Progress",
        home_title2: "Working for the benefit of the client",
        home_title3: "Our creed is reliability, stability, Swiss quality",
        home_title4: "Change for the better starts with us. Open the way to your success!",
        home_title5: "Save. Preserve. Grow",
        home_title6: "We work for your benefit 24/7",
        home_title7: "Your financial freedom is here",
        home_title8: "We manage the finances for your welfare",
        home_title9: "The right decision is the key to success",
        about_title: "About company",
        about_media: "Our media" 
    };
}
